### ISSUE TITLE
Unable to find docker image

### ISSUE THREAD

**Issue by foopang** [Madmous/madClones#7]
Hi, I cannot run the server application inside docker in `develop` branch. Please see below:

```
➜  server git:(develop) docker-compose up
Creating network "server_trellodb" with the default driver
Creating network "server_usersdb" with the default driver
Creating network "server_trellousers" with the default driver
Creating volume "server_mongo" with default driver
Creating volume "server_mysql" with default driver
Pulling mysql (mysql:latest)...
latest: Pulling from library/mysql
cd0a524342ef: Pull complete
d9c95f06c17e: Pull complete
46b2d578f59a: Pull complete
10fbc2bcc6e9: Pull complete
91b1a29c3956: Pull complete
5bf9316bd602: Pull complete
69bd23f08b55: Pull complete
4fb778132e94: Pull complete
6913628d7744: Pull complete
a477f36dc2e0: Pull complete
c954124ae935: Pull complete
Digest: sha256:e44b9a3ae88db013a3e8571a89998678ba44676ed4ae9f54714fd31e108f8b58
Status: Downloaded newer image for mysql:latest
Pulling usersmicroservice (madmous/usersmicroservice:latest)...
ERROR: repository madmous/usersmicroservice not found: does not exist or no pull access
```

**Comment by Madmous** [comment]
Hello i am not home currently to check what is on my docker hub repo but I am sure I haven't pushed it yet.

Follow these steps when you are in the server folder.
1. cd trello-microservice
2. docker build -t madmous/trellomicroservice .
3. cd ../users-microservice
4. docker built -t madmous/usersmicroservice
5. cd ..
6. mysql.server stop (command tested on mac. Since I am mapping the port 3306 of the mysql docker image, you need to make sure your local mysql is not running already on that same port).
6. docker-compose up 

It should be working after that. I will add these steps to the readme because they re lackign instructions.

**Comment by Madmous** [comment]
You are welcome.
